image:
  repository: ghcr.io/mlflow/mlflow
  tag: v2.16.0
  pullPolicy: IfNotPresent

service:
  port: 5000

persistence:
  size: 5Gi
  storageClass: ""

gcs:
  bucket: "gs://geo-mlops-artifacts-rsmrtk"
  secretName: "mlflow-gcs-key"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
