# Production overrides

postgres:
  auth:
    password: ""

geocoder:
  image:
    tag: latest  # GitHub Actions updates this field automatically on each push
  ingress:
    host: "geo.34.40.52.167.nip.io"

ml-svc:
  image:
    tag: latest

mlflow:
  persistence:
    size: 5Gi
